name: "Podcast Generator"
author: "Anton Ov"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: The commiter's email address
    required: ture
    default: ${{github.actor }}@localhost
  name:
    description: The committer's name
    required: ture
    default: ${{github.actor}}